---
title: PA1.1 Git history exercise 9
config:
  gitGraph:
    rotateCommitLabel: false
---
gitGraph TB:
   commit id: "Initial commit"
   commit id: "Add deadline"
   commit id: "Updated 10_commit_local.md, added my_first_file.md"
   commit id: "Updated 12_commit_online.md"